default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: "root"
  host: mysql

development:
  <<: *default
  database: chatAppDev

test:
  <<: *default
  database: chatAppTest

production:
  <<: *default
  database: chatApp
